// Code generated by MockGen. DO NOT EDIT.
// Source: internal/shared/storage/storage.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	storage "go-modular-monolith/internal/shared/storage"
	io "io"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockStorageService is a mock of StorageService interface.
type MockStorageService struct {
	ctrl     *gomock.Controller
	recorder *MockStorageServiceMockRecorder
}

// MockStorageServiceMockRecorder is the mock recorder for MockStorageService.
type MockStorageServiceMockRecorder struct {
	mock *MockStorageService
}

// NewMockStorageService creates a new mock instance.
func NewMockStorageService(ctrl *gomock.Controller) *MockStorageService {
	mock := &MockStorageService{ctrl: ctrl}
	mock.recorder = &MockStorageServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorageService) EXPECT() *MockStorageServiceMockRecorder {
	return m.recorder
}

// Copy mocks base method.
func (m *MockStorageService) Copy(ctx context.Context, sourcePath, destPath string) (*storage.StorageObject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Copy", ctx, sourcePath, destPath)
	ret0, _ := ret[0].(*storage.StorageObject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Copy indicates an expected call of Copy.
func (mr *MockStorageServiceMockRecorder) Copy(ctx, sourcePath, destPath interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Copy", reflect.TypeOf((*MockStorageService)(nil).Copy), ctx, sourcePath, destPath)
}

// Delete mocks base method.
func (m *MockStorageService) Delete(ctx context.Context, path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, path)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockStorageServiceMockRecorder) Delete(ctx, path interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockStorageService)(nil).Delete), ctx, path)
}

// DeletePrefix mocks base method.
func (m *MockStorageService) DeletePrefix(ctx context.Context, prefix string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePrefix", ctx, prefix)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePrefix indicates an expected call of DeletePrefix.
func (mr *MockStorageServiceMockRecorder) DeletePrefix(ctx, prefix interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePrefix", reflect.TypeOf((*MockStorageService)(nil).DeletePrefix), ctx, prefix)
}

// Download mocks base method.
func (m *MockStorageService) Download(ctx context.Context, path string) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Download", ctx, path)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Download indicates an expected call of Download.
func (mr *MockStorageServiceMockRecorder) Download(ctx, path interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Download", reflect.TypeOf((*MockStorageService)(nil).Download), ctx, path)
}

// Exists mocks base method.
func (m *MockStorageService) Exists(ctx context.Context, path string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, path)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockStorageServiceMockRecorder) Exists(ctx, path interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockStorageService)(nil).Exists), ctx, path)
}

// GetBytes mocks base method.
func (m *MockStorageService) GetBytes(ctx context.Context, path string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBytes", ctx, path)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBytes indicates an expected call of GetBytes.
func (mr *MockStorageServiceMockRecorder) GetBytes(ctx, path interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBytes", reflect.TypeOf((*MockStorageService)(nil).GetBytes), ctx, path)
}

// GetObject mocks base method.
func (m *MockStorageService) GetObject(ctx context.Context, path string) (*storage.StorageObject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObject", ctx, path)
	ret0, _ := ret[0].(*storage.StorageObject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObject indicates an expected call of GetObject.
func (mr *MockStorageServiceMockRecorder) GetObject(ctx, path interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObject", reflect.TypeOf((*MockStorageService)(nil).GetObject), ctx, path)
}

// GetPresignedURL mocks base method.
func (m *MockStorageService) GetPresignedURL(ctx context.Context, path string, expiration time.Duration) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPresignedURL", ctx, path, expiration)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPresignedURL indicates an expected call of GetPresignedURL.
func (mr *MockStorageServiceMockRecorder) GetPresignedURL(ctx, path, expiration interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPresignedURL", reflect.TypeOf((*MockStorageService)(nil).GetPresignedURL), ctx, path, expiration)
}

// Health mocks base method.
func (m *MockStorageService) Health(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Health", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Health indicates an expected call of Health.
func (mr *MockStorageServiceMockRecorder) Health(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Health", reflect.TypeOf((*MockStorageService)(nil).Health), ctx)
}

// ListObjects mocks base method.
func (m *MockStorageService) ListObjects(ctx context.Context, prefix string, recursive bool) ([]*storage.StorageObject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListObjects", ctx, prefix, recursive)
	ret0, _ := ret[0].([]*storage.StorageObject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListObjects indicates an expected call of ListObjects.
func (mr *MockStorageServiceMockRecorder) ListObjects(ctx, prefix, recursive interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListObjects", reflect.TypeOf((*MockStorageService)(nil).ListObjects), ctx, prefix, recursive)
}

// Upload mocks base method.
func (m *MockStorageService) Upload(ctx context.Context, path string, reader io.Reader, opts *storage.UploadOptions) (*storage.StorageObject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upload", ctx, path, reader, opts)
	ret0, _ := ret[0].(*storage.StorageObject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upload indicates an expected call of Upload.
func (mr *MockStorageServiceMockRecorder) Upload(ctx, path, reader, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*MockStorageService)(nil).Upload), ctx, path, reader, opts)
}

// UploadBytes mocks base method.
func (m *MockStorageService) UploadBytes(ctx context.Context, path string, data []byte, opts *storage.UploadOptions) (*storage.StorageObject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadBytes", ctx, path, data, opts)
	ret0, _ := ret[0].(*storage.StorageObject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadBytes indicates an expected call of UploadBytes.
func (mr *MockStorageServiceMockRecorder) UploadBytes(ctx, path, data, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadBytes", reflect.TypeOf((*MockStorageService)(nil).UploadBytes), ctx, path, data, opts)
}
