// Code generated by MockGen. DO NOT EDIT.
// Source: internal/app/worker/registrar.go

// Package mocks is a generated GoMock package.
package mocks

import (
	worker "go-modular-monolith/internal/shared/worker"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockModuleWorkerProvider is a mock of ModuleWorkerProvider interface.
type MockModuleWorkerProvider struct {
	ctrl     *gomock.Controller
	recorder *MockModuleWorkerProviderMockRecorder
}

// MockModuleWorkerProviderMockRecorder is the mock recorder for MockModuleWorkerProvider.
type MockModuleWorkerProviderMockRecorder struct {
	mock *MockModuleWorkerProvider
}

// NewMockModuleWorkerProvider creates a new mock instance.
func NewMockModuleWorkerProvider(ctrl *gomock.Controller) *MockModuleWorkerProvider {
	mock := &MockModuleWorkerProvider{ctrl: ctrl}
	mock.recorder = &MockModuleWorkerProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockModuleWorkerProvider) EXPECT() *MockModuleWorkerProviderMockRecorder {
	return m.recorder
}

// GetCronJobDefinitions mocks base method.
func (m *MockModuleWorkerProvider) GetCronJobDefinitions(emailNotificationsEnabled bool) []worker.CronJobDefinition {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCronJobDefinitions", emailNotificationsEnabled)
	ret0, _ := ret[0].([]worker.CronJobDefinition)
	return ret0
}

// GetCronJobDefinitions indicates an expected call of GetCronJobDefinitions.
func (mr *MockModuleWorkerProviderMockRecorder) GetCronJobDefinitions(emailNotificationsEnabled interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCronJobDefinitions", reflect.TypeOf((*MockModuleWorkerProvider)(nil).GetCronJobDefinitions), emailNotificationsEnabled)
}

// GetTaskDefinitions mocks base method.
func (m *MockModuleWorkerProvider) GetTaskDefinitions(userRepository, emailService interface{}, emailNotificationsEnabled, dataExportEnabled, reportGenerationEnabled bool) []worker.TaskDefinition {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskDefinitions", userRepository, emailService, emailNotificationsEnabled, dataExportEnabled, reportGenerationEnabled)
	ret0, _ := ret[0].([]worker.TaskDefinition)
	return ret0
}

// GetTaskDefinitions indicates an expected call of GetTaskDefinitions.
func (mr *MockModuleWorkerProviderMockRecorder) GetTaskDefinitions(userRepository, emailService, emailNotificationsEnabled, dataExportEnabled, reportGenerationEnabled interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskDefinitions", reflect.TypeOf((*MockModuleWorkerProvider)(nil).GetTaskDefinitions), userRepository, emailService, emailNotificationsEnabled, dataExportEnabled, reportGenerationEnabled)
}
