// Code generated by MockGen. DO NOT EDIT.
// Source: internal/modules/auth/domain/interfaces.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/kamil5b/go-ptse-monolith/internal/modules/auth/domain"
	context0 "github.com/kamil5b/go-ptse-monolith/internal/shared/context"

	gomock "github.com/golang/mock/gomock"
)

// MockHandler is a mock of Handler interface.
type MockHandler struct {
	ctrl     *gomock.Controller
	recorder *MockHandlerMockRecorder
}

// MockHandlerMockRecorder is the mock recorder for MockHandler.
type MockHandlerMockRecorder struct {
	mock *MockHandler
}

// NewMockHandler creates a new mock instance.
func NewMockHandler(ctrl *gomock.Controller) *MockHandler {
	mock := &MockHandler{ctrl: ctrl}
	mock.recorder = &MockHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHandler) EXPECT() *MockHandlerMockRecorder {
	return m.recorder
}

// ChangePassword mocks base method.
func (m *MockHandler) ChangePassword(c context0.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangePassword", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangePassword indicates an expected call of ChangePassword.
func (mr *MockHandlerMockRecorder) ChangePassword(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangePassword", reflect.TypeOf((*MockHandler)(nil).ChangePassword), c)
}

// GetProfile mocks base method.
func (m *MockHandler) GetProfile(c context0.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProfile", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetProfile indicates an expected call of GetProfile.
func (mr *MockHandlerMockRecorder) GetProfile(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfile", reflect.TypeOf((*MockHandler)(nil).GetProfile), c)
}

// GetSessions mocks base method.
func (m *MockHandler) GetSessions(c context0.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessions", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetSessions indicates an expected call of GetSessions.
func (mr *MockHandlerMockRecorder) GetSessions(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessions", reflect.TypeOf((*MockHandler)(nil).GetSessions), c)
}

// Login mocks base method.
func (m *MockHandler) Login(c context0.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// Login indicates an expected call of Login.
func (mr *MockHandlerMockRecorder) Login(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockHandler)(nil).Login), c)
}

// Logout mocks base method.
func (m *MockHandler) Logout(c context0.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// Logout indicates an expected call of Logout.
func (mr *MockHandlerMockRecorder) Logout(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockHandler)(nil).Logout), c)
}

// RefreshToken mocks base method.
func (m *MockHandler) RefreshToken(c context0.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshToken", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// RefreshToken indicates an expected call of RefreshToken.
func (mr *MockHandlerMockRecorder) RefreshToken(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshToken", reflect.TypeOf((*MockHandler)(nil).RefreshToken), c)
}

// Register mocks base method.
func (m *MockHandler) Register(c context0.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// Register indicates an expected call of Register.
func (mr *MockHandlerMockRecorder) Register(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockHandler)(nil).Register), c)
}

// RevokeAllSessions mocks base method.
func (m *MockHandler) RevokeAllSessions(c context0.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeAllSessions", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeAllSessions indicates an expected call of RevokeAllSessions.
func (mr *MockHandlerMockRecorder) RevokeAllSessions(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeAllSessions", reflect.TypeOf((*MockHandler)(nil).RevokeAllSessions), c)
}

// RevokeSession mocks base method.
func (m *MockHandler) RevokeSession(c context0.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeSession", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeSession indicates an expected call of RevokeSession.
func (mr *MockHandlerMockRecorder) RevokeSession(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeSession", reflect.TypeOf((*MockHandler)(nil).RevokeSession), c)
}

// ValidateToken mocks base method.
func (m *MockHandler) ValidateToken(c context0.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateToken", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateToken indicates an expected call of ValidateToken.
func (mr *MockHandlerMockRecorder) ValidateToken(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateToken", reflect.TypeOf((*MockHandler)(nil).ValidateToken), c)
}

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// ChangePassword mocks base method.
func (m *MockService) ChangePassword(ctx context.Context, userID string, req *domain.ChangePasswordRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangePassword", ctx, userID, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangePassword indicates an expected call of ChangePassword.
func (mr *MockServiceMockRecorder) ChangePassword(ctx, userID, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangePassword", reflect.TypeOf((*MockService)(nil).ChangePassword), ctx, userID, req)
}

// ConfirmResetPassword mocks base method.
func (m *MockService) ConfirmResetPassword(ctx context.Context, req *domain.ConfirmResetPasswordRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfirmResetPassword", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConfirmResetPassword indicates an expected call of ConfirmResetPassword.
func (mr *MockServiceMockRecorder) ConfirmResetPassword(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmResetPassword", reflect.TypeOf((*MockService)(nil).ConfirmResetPassword), ctx, req)
}

// GenerateAccessToken mocks base method.
func (m *MockService) GenerateAccessToken(claims *domain.TokenClaims) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateAccessToken", claims)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateAccessToken indicates an expected call of GenerateAccessToken.
func (mr *MockServiceMockRecorder) GenerateAccessToken(claims interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateAccessToken", reflect.TypeOf((*MockService)(nil).GenerateAccessToken), claims)
}

// GenerateRefreshToken mocks base method.
func (m *MockService) GenerateRefreshToken(userID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateRefreshToken", userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateRefreshToken indicates an expected call of GenerateRefreshToken.
func (mr *MockServiceMockRecorder) GenerateRefreshToken(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateRefreshToken", reflect.TypeOf((*MockService)(nil).GenerateRefreshToken), userID)
}

// GetSessions mocks base method.
func (m *MockService) GetSessions(ctx context.Context, userID string) (*domain.SessionListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessions", ctx, userID)
	ret0, _ := ret[0].(*domain.SessionListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSessions indicates an expected call of GetSessions.
func (mr *MockServiceMockRecorder) GetSessions(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessions", reflect.TypeOf((*MockService)(nil).GetSessions), ctx, userID)
}

// HashPassword mocks base method.
func (m *MockService) HashPassword(password string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HashPassword", password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HashPassword indicates an expected call of HashPassword.
func (mr *MockServiceMockRecorder) HashPassword(password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HashPassword", reflect.TypeOf((*MockService)(nil).HashPassword), password)
}

// Login mocks base method.
func (m *MockService) Login(ctx context.Context, req *domain.LoginRequest, userAgent, ipAddress string) (*domain.LoginResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, req, userAgent, ipAddress)
	ret0, _ := ret[0].(*domain.LoginResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockServiceMockRecorder) Login(ctx, req, userAgent, ipAddress interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockService)(nil).Login), ctx, req, userAgent, ipAddress)
}

// Logout mocks base method.
func (m *MockService) Logout(ctx context.Context, userID string, req *domain.LogoutRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout", ctx, userID, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Logout indicates an expected call of Logout.
func (mr *MockServiceMockRecorder) Logout(ctx, userID, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockService)(nil).Logout), ctx, userID, req)
}

// ParseToken mocks base method.
func (m *MockService) ParseToken(token string) (*domain.TokenClaims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseToken", token)
	ret0, _ := ret[0].(*domain.TokenClaims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseToken indicates an expected call of ParseToken.
func (mr *MockServiceMockRecorder) ParseToken(token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseToken", reflect.TypeOf((*MockService)(nil).ParseToken), token)
}

// RefreshToken mocks base method.
func (m *MockService) RefreshToken(ctx context.Context, refreshToken string) (*domain.RefreshTokenResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshToken", ctx, refreshToken)
	ret0, _ := ret[0].(*domain.RefreshTokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefreshToken indicates an expected call of RefreshToken.
func (mr *MockServiceMockRecorder) RefreshToken(ctx, refreshToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshToken", reflect.TypeOf((*MockService)(nil).RefreshToken), ctx, refreshToken)
}

// Register mocks base method.
func (m *MockService) Register(ctx context.Context, req *domain.RegisterRequest) (*domain.RegisterResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, req)
	ret0, _ := ret[0].(*domain.RegisterResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockServiceMockRecorder) Register(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockService)(nil).Register), ctx, req)
}

// ResetPassword mocks base method.
func (m *MockService) ResetPassword(ctx context.Context, req *domain.ResetPasswordRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetPassword", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetPassword indicates an expected call of ResetPassword.
func (mr *MockServiceMockRecorder) ResetPassword(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetPassword", reflect.TypeOf((*MockService)(nil).ResetPassword), ctx, req)
}

// RevokeAllSessions mocks base method.
func (m *MockService) RevokeAllSessions(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeAllSessions", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeAllSessions indicates an expected call of RevokeAllSessions.
func (mr *MockServiceMockRecorder) RevokeAllSessions(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeAllSessions", reflect.TypeOf((*MockService)(nil).RevokeAllSessions), ctx, userID)
}

// RevokeSession mocks base method.
func (m *MockService) RevokeSession(ctx context.Context, userID, sessionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeSession", ctx, userID, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeSession indicates an expected call of RevokeSession.
func (mr *MockServiceMockRecorder) RevokeSession(ctx, userID, sessionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeSession", reflect.TypeOf((*MockService)(nil).RevokeSession), ctx, userID, sessionID)
}

// ValidateToken mocks base method.
func (m *MockService) ValidateToken(ctx context.Context, token string) (*domain.ValidateTokenResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateToken", ctx, token)
	ret0, _ := ret[0].(*domain.ValidateTokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateToken indicates an expected call of ValidateToken.
func (mr *MockServiceMockRecorder) ValidateToken(ctx, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateToken", reflect.TypeOf((*MockService)(nil).ValidateToken), ctx, token)
}

// VerifyPassword mocks base method.
func (m *MockService) VerifyPassword(hashedPassword, password string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyPassword", hashedPassword, password)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerifyPassword indicates an expected call of VerifyPassword.
func (mr *MockServiceMockRecorder) VerifyPassword(hashedPassword, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyPassword", reflect.TypeOf((*MockService)(nil).VerifyPassword), hashedPassword, password)
}

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CreateCredential mocks base method.
func (m *MockRepository) CreateCredential(ctx context.Context, cred *domain.Credential) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCredential", ctx, cred)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateCredential indicates an expected call of CreateCredential.
func (mr *MockRepositoryMockRecorder) CreateCredential(ctx, cred interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCredential", reflect.TypeOf((*MockRepository)(nil).CreateCredential), ctx, cred)
}

// CreateSession mocks base method.
func (m *MockRepository) CreateSession(ctx context.Context, session *domain.Session) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", ctx, session)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockRepositoryMockRecorder) CreateSession(ctx, session interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockRepository)(nil).CreateSession), ctx, session)
}

// DeferErrorContext mocks base method.
func (m *MockRepository) DeferErrorContext(ctx context.Context, err error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeferErrorContext", ctx, err)
}

// DeferErrorContext indicates an expected call of DeferErrorContext.
func (mr *MockRepositoryMockRecorder) DeferErrorContext(ctx, err interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeferErrorContext", reflect.TypeOf((*MockRepository)(nil).DeferErrorContext), ctx, err)
}

// DeleteExpiredSessions mocks base method.
func (m *MockRepository) DeleteExpiredSessions(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpiredSessions", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteExpiredSessions indicates an expected call of DeleteExpiredSessions.
func (mr *MockRepositoryMockRecorder) DeleteExpiredSessions(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpiredSessions", reflect.TypeOf((*MockRepository)(nil).DeleteExpiredSessions), ctx)
}

// GetCredentialByEmail mocks base method.
func (m *MockRepository) GetCredentialByEmail(ctx context.Context, email string) (*domain.Credential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCredentialByEmail", ctx, email)
	ret0, _ := ret[0].(*domain.Credential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCredentialByEmail indicates an expected call of GetCredentialByEmail.
func (mr *MockRepositoryMockRecorder) GetCredentialByEmail(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCredentialByEmail", reflect.TypeOf((*MockRepository)(nil).GetCredentialByEmail), ctx, email)
}

// GetCredentialByUserID mocks base method.
func (m *MockRepository) GetCredentialByUserID(ctx context.Context, userID string) (*domain.Credential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCredentialByUserID", ctx, userID)
	ret0, _ := ret[0].(*domain.Credential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCredentialByUserID indicates an expected call of GetCredentialByUserID.
func (mr *MockRepositoryMockRecorder) GetCredentialByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCredentialByUserID", reflect.TypeOf((*MockRepository)(nil).GetCredentialByUserID), ctx, userID)
}

// GetCredentialByUsername mocks base method.
func (m *MockRepository) GetCredentialByUsername(ctx context.Context, username string) (*domain.Credential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCredentialByUsername", ctx, username)
	ret0, _ := ret[0].(*domain.Credential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCredentialByUsername indicates an expected call of GetCredentialByUsername.
func (mr *MockRepositoryMockRecorder) GetCredentialByUsername(ctx, username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCredentialByUsername", reflect.TypeOf((*MockRepository)(nil).GetCredentialByUsername), ctx, username)
}

// GetSessionByID mocks base method.
func (m *MockRepository) GetSessionByID(ctx context.Context, id string) (*domain.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionByID", ctx, id)
	ret0, _ := ret[0].(*domain.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSessionByID indicates an expected call of GetSessionByID.
func (mr *MockRepositoryMockRecorder) GetSessionByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionByID", reflect.TypeOf((*MockRepository)(nil).GetSessionByID), ctx, id)
}

// GetSessionByToken mocks base method.
func (m *MockRepository) GetSessionByToken(ctx context.Context, token string) (*domain.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionByToken", ctx, token)
	ret0, _ := ret[0].(*domain.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSessionByToken indicates an expected call of GetSessionByToken.
func (mr *MockRepositoryMockRecorder) GetSessionByToken(ctx, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionByToken", reflect.TypeOf((*MockRepository)(nil).GetSessionByToken), ctx, token)
}

// GetSessionsByUserID mocks base method.
func (m *MockRepository) GetSessionsByUserID(ctx context.Context, userID string) ([]domain.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionsByUserID", ctx, userID)
	ret0, _ := ret[0].([]domain.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSessionsByUserID indicates an expected call of GetSessionsByUserID.
func (mr *MockRepositoryMockRecorder) GetSessionsByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionsByUserID", reflect.TypeOf((*MockRepository)(nil).GetSessionsByUserID), ctx, userID)
}

// RevokeAllUserSessions mocks base method.
func (m *MockRepository) RevokeAllUserSessions(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeAllUserSessions", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeAllUserSessions indicates an expected call of RevokeAllUserSessions.
func (mr *MockRepositoryMockRecorder) RevokeAllUserSessions(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeAllUserSessions", reflect.TypeOf((*MockRepository)(nil).RevokeAllUserSessions), ctx, userID)
}

// RevokeSession mocks base method.
func (m *MockRepository) RevokeSession(ctx context.Context, sessionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeSession", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeSession indicates an expected call of RevokeSession.
func (mr *MockRepositoryMockRecorder) RevokeSession(ctx, sessionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeSession", reflect.TypeOf((*MockRepository)(nil).RevokeSession), ctx, sessionID)
}

// StartContext mocks base method.
func (m *MockRepository) StartContext(ctx context.Context) context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartContext", ctx)
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// StartContext indicates an expected call of StartContext.
func (mr *MockRepositoryMockRecorder) StartContext(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartContext", reflect.TypeOf((*MockRepository)(nil).StartContext), ctx)
}

// UpdateCredential mocks base method.
func (m *MockRepository) UpdateCredential(ctx context.Context, cred *domain.Credential) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCredential", ctx, cred)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCredential indicates an expected call of UpdateCredential.
func (mr *MockRepositoryMockRecorder) UpdateCredential(ctx, cred interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCredential", reflect.TypeOf((*MockRepository)(nil).UpdateCredential), ctx, cred)
}

// UpdateLastLogin mocks base method.
func (m *MockRepository) UpdateLastLogin(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLastLogin", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLastLogin indicates an expected call of UpdateLastLogin.
func (mr *MockRepositoryMockRecorder) UpdateLastLogin(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastLogin", reflect.TypeOf((*MockRepository)(nil).UpdateLastLogin), ctx, userID)
}

// UpdatePassword mocks base method.
func (m *MockRepository) UpdatePassword(ctx context.Context, userID, passwordHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePassword", ctx, userID, passwordHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePassword indicates an expected call of UpdatePassword.
func (mr *MockRepositoryMockRecorder) UpdatePassword(ctx, userID, passwordHash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePassword", reflect.TypeOf((*MockRepository)(nil).UpdatePassword), ctx, userID, passwordHash)
}

// MockMiddleware is a mock of Middleware interface.
type MockMiddleware struct {
	ctrl     *gomock.Controller
	recorder *MockMiddlewareMockRecorder
}

// MockMiddlewareMockRecorder is the mock recorder for MockMiddleware.
type MockMiddlewareMockRecorder struct {
	mock *MockMiddleware
}

// NewMockMiddleware creates a new mock instance.
func NewMockMiddleware(ctrl *gomock.Controller) *MockMiddleware {
	mock := &MockMiddleware{ctrl: ctrl}
	mock.recorder = &MockMiddlewareMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMiddleware) EXPECT() *MockMiddlewareMockRecorder {
	return m.recorder
}

// Authenticate mocks base method.
func (m *MockMiddleware) Authenticate() func(func(context0.Context) error) func(context0.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authenticate")
	ret0, _ := ret[0].(func(func(context0.Context) error) func(context0.Context) error)
	return ret0
}

// Authenticate indicates an expected call of Authenticate.
func (mr *MockMiddlewareMockRecorder) Authenticate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authenticate", reflect.TypeOf((*MockMiddleware)(nil).Authenticate))
}

// OptionalAuth mocks base method.
func (m *MockMiddleware) OptionalAuth() func(func(context0.Context) error) func(context0.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OptionalAuth")
	ret0, _ := ret[0].(func(func(context0.Context) error) func(context0.Context) error)
	return ret0
}

// OptionalAuth indicates an expected call of OptionalAuth.
func (mr *MockMiddlewareMockRecorder) OptionalAuth() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OptionalAuth", reflect.TypeOf((*MockMiddleware)(nil).OptionalAuth))
}

// RequireAuth mocks base method.
func (m *MockMiddleware) RequireAuth() func(func(context0.Context) error) func(context0.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequireAuth")
	ret0, _ := ret[0].(func(func(context0.Context) error) func(context0.Context) error)
	return ret0
}

// RequireAuth indicates an expected call of RequireAuth.
func (mr *MockMiddlewareMockRecorder) RequireAuth() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequireAuth", reflect.TypeOf((*MockMiddleware)(nil).RequireAuth))
}

// RequireRoles mocks base method.
func (m *MockMiddleware) RequireRoles(roles ...string) func(func(context0.Context) error) func(context0.Context) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range roles {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RequireRoles", varargs...)
	ret0, _ := ret[0].(func(func(context0.Context) error) func(context0.Context) error)
	return ret0
}

// RequireRoles indicates an expected call of RequireRoles.
func (mr *MockMiddlewareMockRecorder) RequireRoles(roles ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequireRoles", reflect.TypeOf((*MockMiddleware)(nil).RequireRoles), roles...)
}

// MockUserCreator is a mock of UserCreator interface.
type MockUserCreator struct {
	ctrl     *gomock.Controller
	recorder *MockUserCreatorMockRecorder
}

// MockUserCreatorMockRecorder is the mock recorder for MockUserCreator.
type MockUserCreatorMockRecorder struct {
	mock *MockUserCreator
}

// NewMockUserCreator creates a new mock instance.
func NewMockUserCreator(ctrl *gomock.Controller) *MockUserCreator {
	mock := &MockUserCreator{ctrl: ctrl}
	mock.recorder = &MockUserCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserCreator) EXPECT() *MockUserCreatorMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockUserCreator) CreateUser(ctx context.Context, user *domain.NewUser) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserCreatorMockRecorder) CreateUser(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserCreator)(nil).CreateUser), ctx, user)
}
