// Code generated by MockGen. DO NOT EDIT.
// Source: internal/shared/email/email.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	email "go-modular-monolith/internal/shared/email"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockEmailService is a mock of EmailService interface.
type MockEmailService struct {
	ctrl     *gomock.Controller
	recorder *MockEmailServiceMockRecorder
}

// MockEmailServiceMockRecorder is the mock recorder for MockEmailService.
type MockEmailServiceMockRecorder struct {
	mock *MockEmailService
}

// NewMockEmailService creates a new mock instance.
func NewMockEmailService(ctrl *gomock.Controller) *MockEmailService {
	mock := &MockEmailService{ctrl: ctrl}
	mock.recorder = &MockEmailServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailService) EXPECT() *MockEmailServiceMockRecorder {
	return m.recorder
}

// Health mocks base method.
func (m *MockEmailService) Health(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Health", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Health indicates an expected call of Health.
func (mr *MockEmailServiceMockRecorder) Health(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Health", reflect.TypeOf((*MockEmailService)(nil).Health), ctx)
}

// Send mocks base method.
func (m *MockEmailService) Send(ctx context.Context, email *email.Email) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, email)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockEmailServiceMockRecorder) Send(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockEmailService)(nil).Send), ctx, email)
}

// SendBatch mocks base method.
func (m *MockEmailService) SendBatch(ctx context.Context, emails []*email.Email) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendBatch", ctx, emails)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendBatch indicates an expected call of SendBatch.
func (mr *MockEmailServiceMockRecorder) SendBatch(ctx, emails interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendBatch", reflect.TypeOf((*MockEmailService)(nil).SendBatch), ctx, emails)
}

// SendTemplate mocks base method.
func (m *MockEmailService) SendTemplate(ctx context.Context, to []string, templateID string, data map[string]interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendTemplate", ctx, to, templateID, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendTemplate indicates an expected call of SendTemplate.
func (mr *MockEmailServiceMockRecorder) SendTemplate(ctx, to, templateID, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendTemplate", reflect.TypeOf((*MockEmailService)(nil).SendTemplate), ctx, to, templateID, data)
}

// ValidateEmail mocks base method.
func (m *MockEmailService) ValidateEmail(email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateEmail", email)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateEmail indicates an expected call of ValidateEmail.
func (mr *MockEmailServiceMockRecorder) ValidateEmail(email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateEmail", reflect.TypeOf((*MockEmailService)(nil).ValidateEmail), email)
}
